config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations"}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'startpage/index'
  root 'startpage#index'

  get 'politic', to: 'politic#index.html', as: :politic
  get 'delivery', to: 'politic#delivery.html', as: :delivery
  get 'credits', to: 'politic#credits.html.erb', as: :credits

  resources :products
  resources :users
  resources :categories
  resources :carts
  resources :orders
  resources :accias
  resources :positions
  resources :reviews

  get 'update_all', to: 'products#update_all', as: :products_update_all
  get '403', to: 'errors#403.html', as: :_403

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accia.rb
class Accia < ApplicationRecord

  has_many :products

  has_one_attached :image


  def to_param
    "#{id}-#{slug}"
  end
  
end

app/models/accion_iterator.rb
class AccionIterator < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user
  has_many :positions
  has_many :products, through: :positions

  def to_param
    "#{id}-#{slug}"
  end


  private

  def set_slug
    self.slug = self.user.name.to_s.parameterize + "cart"
  end
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products
  has_ancestry

  validates :name, presence: true

  def to_param
    "#{id}-#{slug}"
  end


  private

  def set_slug
    self.slug = self.name.to_s.parameterize
  end
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
  has_many :positions
  has_many :products, through: :positions

  def to_param
    "#{id}-#{slug}"
  end

  private

  def set_slug
    self.slug = self.user.name.to_s.parameterize + "order" + self.id
  end
end

app/models/position.rb
class Position < ApplicationRecord

  validates :quantity, presence: true, numericality: { greater_than: 0, less_than: 100 }

  belongs_to :product
  belongs_to :cart
  belongs_to :order
end

app/models/post.rb
class Post < ApplicationRecord

  def to_param
    "#{id}-#{slug}"
  end


  private

  def set_slug
    self.slug = self.title.to_s.parameterize
  end
end

app/models/product.rb
class Product < ApplicationRecord

  validates :name, length: { maximum: 52,
   too_long: "Наименование не должно превышать 52 символов" }

  belongs_to :category
  belongs_to :accia

  has_one :productcount

  has_many :positions
  has_many :carts, through: :positions
  has_many :orders, through: :positions

  has_one_attached :image

  def to_param
    "#{id}-#{slug}"
  end

  private

  def set_slug
    self.slug = self.name.to_s.parameterize
  end

end

app/models/productcount.rb
class Productcount < ApplicationRecord
    belongs_to :product
end

app/models/review.rb
class Review < ApplicationRecord

  def to_param
    "#{id}-#{slug}"
  end

  private

  def set_slug
    self.slug = title.to_s.parameterize
  end 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders
  has_one :cart


  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :confirmable, :validatable

  def to_param
    "#{id}-#{slug}"
  end

  private

  def set_slug
    self.slug = self.name.to_s.parameterize
  end
end

app/controllers/accias_controller.rb
class AcciasController < ApplicationController

  before_action :find_accia, only: [:edit, :show, :update, :destroy]




  def index
    @accias = Accia.where("real = :real and id > :id", { real: true, id: 1 })
  end

  def show
    @products = Product.where("accia_id = :id and real = :real", { id: @accia.id, real: true })
  end

  def new
  end

  def edit

  end

  def destroy
  end

  def update

  end

  def accia_params
    params.require(:accia).permit(:id, :name, :real, :description)
  end

  def product_params
    params.require(:product).permit(:id, :accia_id, :real)
  end

  def find_accia
    @accia = Accia.find(params[:id])
  end

  def after_initialize
    self.start_time ||= Time.now
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :find_cart, only: [:edit, :show, :update, :destroy]

  def index
    
  end

  def show

  end

  def new
  end

  def edit

  end

  def destroy
  end

  def update

  end

  def cart_params
    params.require(:cart).permit(:id, :user_id, :product_ids)
  end

  def position_params
    params.require(:position).permit(:id, :cart_id, :product_id, :quantity)
  end

  def product_params
    params.require(:product).permit(:id, :name, :image)
  end

  def find_cart
    @cart = Cart.find(params[:id])
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
  end

  def show
    @cart = Cart.find(@user.cart_id)
  end

  def edit
  end

  def destroy
  end

  def update
    @user.update(name: params[:user][:name], email: params[:user][:email],  city: params[:user][:city],  telephone: params[:user][:telephone])
    redirect_to user_path(@user)
  end

  def user_params
    params.require(:user).permit(:id, :name, :email, :cart_id, :slug, :telephone, :city)
  end

  def cart_params
    params.require(:cart).permit(:id, :user_id, :slug)
  end

  def position_params
    params.require(:position).permit(:id, :product_id, :quantity)
  end

  def product_params
    params.require(:product).permit(:id, :name, :slug)
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/accia_helper.rb
module AcciaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/startpage_helper.rb
module StartpageHelper
end

app/views/carts/show.html.erb
This is CART ROOM

app/views/users/edit.html.erb
<h1>Редактирование личных данных</h1>

<%= form_for @user do |f| %>

    <%= f.label :name %><br>
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %><br>

    <%= f.label :email %><br>
    <%= f.email_field :email, autocomplete: "email" %><br>

    <%= f.label :city %><br>
    <%= f.text_field :city, autocomplete: "city" %><br>

    <%= f.label :telephone %><br>
    <%= f.phone_field :telephone, autocomplete: "telephone" %><br>

    <%= f.submit "Подтвердить" %>
<% end %>

app/views/users/show.html.erb
<table style="width: 100%;  vertical-align: top;">
  <tr style="vertical-align: top;">
    <th class="all_left_column" style="width: 300px; vertical-align: top;">
      <table style="width: 300px; vertical-align: top;">
        <tr class="spacer"><th>
          <table class="left_column" style="height: 100px; border: 1px solid purple;">
            <tr>
              <% if params[:param1] %>
                    <th class="profile_click" style="font-size: 20px; cursor: pointer;">Профиль</th>
              <% else %>
                    <th class="profile_click" style="font-size: 20px; cursor: pointer; background-color: green;">Профиль</th>
              <% end %>
            </tr>
            <tr>
              <% if params[:param1] %>
                    <th class="cart_click" style="font-size: 20px; cursor: pointer;  background-color: green;">Корзина</th>
              <% else %>
                    <th class="cart_click" style="font-size: 20px; cursor: pointer;">Корзина</th>
              <% end %>
            </tr>
            <tr>
              <th class="order_click" style="font-size: 20px; cursor: pointer;">История заказов</th>
            </tr>
          </table>
        </th></tr>
        <tr class="spacer"><th></th></tr>
      </table>
    </th>

    <th class="all_right_column" >
      <% if params[:param1] %>
            <table class="Cart" style="width: 655px; vertical-align: top;">
      <% else %>
            <table class="Cart" style="display: none; width: 655px; vertical-align: top;">
      <% end %>
          <tr>
            <th style="width: 55px;"> Позиция </th>
            <th style="width: 300px;"> Наименование </th>
            <th style="width: 100px;"> Количество </th>
            <th style="width: 100px;"> Сумма </th>
            <th style="width: 100px;"> Удалить </th>
          </tr>

          <% i=0 %>
          <% full_price = 0 %>

          <% @cart.positions.each do |e| %>
            <tr>
              <th style="width: 55px;"> <%= i = i+1 %> </th>
              <th style="width: 300px;"> <%= Product.find(e.product_id).name %> </th>
              <th style="width: 100px;"> <%= e.quantity %> </th>
              <th style="width: 100px;"> <%= Product.find(e.product_id).action_price ? e.quantity*Product.find(e.product_id).action_price : e.quantity*Product.find(e.product_id).price %> р.</th>
              <% full_price += Product.find(e.product_id).action_price ? e.quantity*Product.find(e.product_id).action_price : e.quantity*Product.find(e.product_id).price %>
              <th style="width: 100px;"> <%= link_to "Удалить", position_path(e.id), :method => :delete  %> </th>
              <br>
            </tr>
          <% end %>

          <tr>
            <th style="width: 55px;"> </th>
            <th style="width: 300px;"> </th>
            <th style="width: 100px;">  </th>
            <th style="width: 100px;"> Итого: <%= full_price %> р. </th>
            <th style="width: 100px;"> Удалить </th>
          </tr>

          <tr><th>
            <%= form_for Order.new do |f| %>
              Адрес:<br>
              <%= f.text_field :adress%> <br>
              <%= f.submit "Оформить заказ" %>
            <% end %>
          </th></tr>
        </table>

      <% if params[:param1] %>
          <table class="Profile" style="vertical-align: top; display: none;">
      <% else %>
          <table class="Profile" style="vertical-align: top;">
      <% end %>

        <tr>
          <th>Имя: <%= @user.name %></th>
        </tr>

        <tr>
          <th>Электронный адрес: <%= @user.email %></th>
        </tr>

        <tr>
          <th>Город: <%= @user.city %></th>
        </tr>

        <tr>
          <th>Телефон: <%= @user.telephone %></th>
        </tr>

        <tr>
          <th><%= button_tag link_to "Правка", edit_user_path(@user.id) %></th>
        </tr>
      </table>

      <table class="Order_history" style="vertical-align: top; display: none;">
        <tr><th>

        <% if current_user.orders %>
          <table>
            <tr>
              <th style="font-size: 16px; width: 150px;">Дата покупки</th>
              <th style="font-size: 16px; width: 200px;">Количество позиций</th>
              <th style="font-size: 16px; width: 100px;">Развернуть</th>
              <th></th>
            </tr>
          </table>

          <% current_user.orders.each do |cur_ord| %>
                <table>
                  <tr>
                    <th style="font-size: 14px; width: 150px; font-weight: normal;"><%= cur_ord.updated_at.strftime("%d / %m / %Y") %></th>
                    <th style="font-size: 14px; width: 200px; font-weight: normal;"><%= cur_ord.positions.size %></th>
                    <%= content_tag(:th, :class => "ordl"+cur_ord.id.to_s, :style => "font-size: 14px; width: 100px; font-weight: normal; cursor: pointer;") do %>
                    Развернуть
                    <% end %>
                    <th></th>
                  </tr>
                </table>
                <%= content_tag(:div, :class => "ordl"+cur_ord.id.to_s, :style => "display: none;") do %>
                    <table style="border: 1px solid purple;">
                      <tr>
                        <th style="font-size: 12px; width: 100px;">Товар</th>
                        <th style="font-size: 12px; width: 100px;">Количество</th>
                        <th style="font-size: 12px; width: 100px;">Стоимость</th>
                        <th></th>
                      </tr>
                      <% cur_ord.positions.each do |cur_pos| %>
                        <tr>
                          <th style="font-size: 12px; width: 150px; color: blue;"><%= link_to cur_pos.product.name, cur_pos.product %></th>
                          <th style="font-size: 12px; width: 200px;"><%= cur_pos.quantity %></th>
                          <th style="font-size: 12px; width: 100px;"><% cur_pos.product.price %></th>
                          <th></th>
                        </tr>
                      <% end %>
                    </table>
                <% end %>
          <% end %>
        <% end %>
        </th></tr>
      </table>

    </th>
  </tr>
</table>

</th>
</tr>
</table>

<script>
  $('.profile_click').on({ click: function() {
                                                $('.Order_history').hide();
                                                $('.order_click').css("background-color", "White");
                                                $('.Cart').hide();
                                                $('.cart_click').css("background-color", "White");
                                                $('.Profile').show();
                                                $('.profile_click').css("background-color", "Green");
                                              }
                                              });
  $('.cart_click').on({ click: function() {
                                                $('.Order_history').hide();
                                                $('.order_click').css("background-color", "White");
                                                $('.Profile').hide();
                                                $('.profile_click').css("background-color", "White");
                                                $('.Cart').show();
                                                $('.cart_click').css("background-color", "Green");
                                              }
                                              });
  $('.order_click').on({ click: function() {
                                                $('.Order_history').show();
                                                $('.order_click').css("background-color", "Green");
                                                $('.Profile').hide();
                                                $('.profile_click').css("background-color", "White");
                                                $('.Cart').hide();
                                                $('.cart_click').css("background-color", "White");
                                              }
                                              });
  $('th[class^="ordl"]').on({ click: function() {
                                                var cl = $(this).attr("class");
                                                if ($(this).text() == "Развернуть") {
                                                  $(this).text("Свернуть");
                                                  $('div').filter('.'+cl+'').show();
                                                }
                                                else {
                                                  $(this).text("Развернуть");
                                                  $('div').filter('.'+cl+'').hide();
                                                }
                                                }
                                            });
</script>