config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations"}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'startpage/index'
  root 'startpage#index'

  get 'politic', to: 'politic#index.html', as: :politic
  get 'delivery', to: 'politic#delivery.html', as: :delivery
  get 'credits', to: 'politic#credits.html.erb', as: :credits

  resources :products
  resources :users
  resources :categories
  resources :carts
  resources :orders
  resources :accias
  resources :positions
  resources :reviews

  get 'update_all', to: 'products#update_all', as: :products_update_all
  get '403', to: 'errors#403.html', as: :_403

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accia.rb
class Accia < ApplicationRecord

  has_many :products

  has_one_attached :image


  def to_param
    "#{id}-#{slug}"
  end
  
end

app/models/accion_iterator.rb
class AccionIterator < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user
  has_many :positions
  has_many :products, through: :positions

  def to_param
    "#{id}-#{slug}"
  end


  private

  def set_slug
    self.slug = self.user.name.to_s.parameterize + "cart"
  end
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products
  has_ancestry

  validates :name, presence: true

  def to_param
    "#{id}-#{slug}"
  end


  private

  def set_slug
    self.slug = self.name.to_s.parameterize
  end
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
  has_many :positions
  has_many :products, through: :positions

  def to_param
    "#{id}-#{slug}"
  end

  private

  def set_slug
    self.slug = self.user.name.to_s.parameterize + "order" + self.id
  end
end

app/models/position.rb
class Position < ApplicationRecord

  validates :quantity, presence: true, numericality: { greater_than: 0, less_than: 100 }

  belongs_to :product
  belongs_to :cart
  belongs_to :order
end

app/models/post.rb
class Post < ApplicationRecord

  def to_param
    "#{id}-#{slug}"
  end


  private

  def set_slug
    self.slug = self.title.to_s.parameterize
  end
end

app/models/product.rb
class Product < ApplicationRecord

  validates :name, length: { maximum: 52,
   too_long: "Наименование не должно превышать 52 символов" }

  belongs_to :category
  belongs_to :accia

  has_one :productcount

  has_many :positions
  has_many :carts, through: :positions
  has_many :orders, through: :positions

  has_one_attached :image

  def to_param
    "#{id}-#{slug}"
  end

  private

  def set_slug
    self.slug = self.name.to_s.parameterize
  end

end

app/models/productcount.rb
class Productcount < ApplicationRecord
    belongs_to :product
end

app/models/review.rb
class Review < ApplicationRecord

  def to_param
    "#{id}-#{slug}"
  end

  private

  def set_slug
    self.slug = title.to_s.parameterize
  end 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders
  has_one :cart


  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :confirmable, :validatable

  def to_param
    "#{id}-#{slug}"
  end

  private

  def set_slug
    self.slug = self.name.to_s.parameterize
  end
end

app/controllers/accias_controller.rb
class AcciasController < ApplicationController

  before_action :find_accia, only: [:edit, :show, :update, :destroy]




  def index
    @accias = Accia.where("real = :real and id > :id", { real: true, id: 1 })
  end

  def show
    @products = Product.where("accia_id = :id and real = :real", { id: @accia.id, real: true })
  end

  def new
  end

  def edit

  end

  def destroy
  end

  def update

  end

  def accia_params
    params.require(:accia).permit(:id, :name, :real, :description)
  end

  def product_params
    params.require(:product).permit(:id, :accia_id, :real)
  end

  def find_accia
    @accia = Accia.find(params[:id])
  end

  def after_initialize
    self.start_time ||= Time.now
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :find_cart, only: [:edit, :show, :update, :destroy]

  def index
    
  end

  def show

  end

  def new
  end

  def edit

  end

  def destroy
  end

  def update

  end

  def cart_params
    params.require(:cart).permit(:id, :user_id, :product_ids)
  end

  def position_params
    params.require(:position).permit(:id, :cart_id, :product_id, :quantity)
  end

  def product_params
    params.require(:product).permit(:id, :name, :image)
  end

  def find_cart
    @cart = Cart.find(params[:id])
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :find_order, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def create
    @order = Order.create(user_id: current_user.id)
    @order.positions = current_user.cart.positions
    params[:order][:adress] ? @order.adress = params[:order][:adress] : ''
    current_user.cart.positions = []
    @order.positions.each do |pos|
      @productc = Productcount.where(product_id: pos.product_id).first
      @productc.count = @productc.count - pos.quantity
      @productc.ordercount = @productc.ordercount + pos.quantity
      @productc.save
    end
    OrderUMailer.with(user: current_user).you_order_email.deliver_now
    OrderUsMailer.with(user: current_user, order: @order).us_order_email.deliver_now
    flash[:notice] = "Ваш заказ поступил в обработку"
    redirect_to user_url(current_user)
  end

  def edit
     #Redurect to "restricted area" message
  end

  def destroy
  end

  def update
  end

  def decrease_counts
  end

  def order_params
    params.require(:order).permit(:id, :user_id, :adress)
  end

  def productcount_params
    params.require(:productcount).permit(:id, :count, :product_id, :ordercount)
  end

  def cart_params
    params.require(:cart).permit(:id)
  end

  def user_params
    params.require(:user).permit(:id, :cart_id, :name, :email)
  end

  def find_order
    @product = Product.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
  end

  def show
    @cart = Cart.find(@user.cart_id)
  end

  def edit
  end

  def destroy
  end

  def update
    @user.update(name: params[:user][:name], email: params[:user][:email],  city: params[:user][:city],  telephone: params[:user][:telephone])
    redirect_to user_path(@user)
  end

  def user_params
    params.require(:user).permit(:id, :name, :email, :cart_id, :slug, :telephone, :city)
  end

  def cart_params
    params.require(:cart).permit(:id, :user_id, :slug)
  end

  def position_params
    params.require(:position).permit(:id, :product_id, :quantity)
  end

  def product_params
    params.require(:product).permit(:id, :name, :slug)
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/accia_helper.rb
module AcciaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/startpage_helper.rb
module StartpageHelper
end

app/views/accias/index.html.erb
<h1 style="color: Blue; margin-left: 10px;">Акции</h1>
<table>
  <% @i = 0 %>
  <tr>
    <% @accias.each do |current_accia| %>
      <% if @i.divmod(3)[1] > 0 %>
          <th><%= link_to image_tag(current_accia.image, size: "440x200", style: "border: 1px solid purple", onMouseover: "this.style='border: 2px solid blue';", onMouseout: "this.style='border: 1px solid purple';"), accia_url(current_accia) %></th>
          <% @i = @i +1 %>
      <% else %>
          </tr> <tr> <th><%= link_to image_tag(current_accia.image, size: "440x200", style: "border: 1px solid purple", onMouseover: "this.style='border: 2px solid blue';", onMouseout: "this.style='border: 1px solid purple';"), accia_url(current_accia) %> </th>
          <% @i = @i +1 %>
      <% end %>
    <% end %>
  </tr>
</table>

<script>
  $(document).ready(function() {
        $("#acti_main").css("background-color", "Green");
      });
</script>

app/views/accias/show.html.erb
<div class="Catalog" style="width: 100%; display: table;">
  <div style="display: table-row;">

    <div style="display: table-cell; width: 330px;">
      <div style="display: table; width: 330px;">
        <div style="display: table-row;">
        <div style="width: 10px; display: table-cell;"> </div>
        <div style="width: 300px; display: table-cell; border: 1px solid Purple;">
          <%= render partial: "shared/tree" %>
        </div>
        <div style="width: 20px; display: table-cell;"> </div>
        </div>
      </div>
    </div>

    <div style="display: table-cell;">
        <h2 style="color: Blue; margin-bottom: 0px;"><%= @accia.name %></h2>
        <div style="margin-bottom: 0px;"><%= @accia.description %></div>
        <hr style="color: Green;">
        <div class="product_list_holder" style="display: table">
            <% i=0 %>
            <% i=i+1 %>
            <% @products.each do |prod| %>
                  <% if i.divmod(3)[1] == 1 %>
                    <%= render inline: '<div style="display: table-row">' %>
                  <% end %>
                  <%= render "shared/productonce", e: prod %>
                  <% if (i.divmod(3)[1] == 0) || (i == @products.size) %>
                    <%= render inline: '</div>' %>
                  <% end %>
                  <% i=i+1 %>
            <% end %>
          </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
        $("#acti_main").css("background-color", "Green");
      });
</script>