config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations"}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'startpage/index'
  root 'startpage#index'

  get 'politic', to: 'politic#index.html', as: :politic
  get 'delivery', to: 'politic#delivery.html', as: :delivery
  get 'credits', to: 'politic#credits.html.erb', as: :credits

  resources :products
  resources :users
  resources :categories
  resources :carts
  resources :orders
  resources :accias
  resources :positions
  resources :reviews

  get 'update_all', to: 'products#update_all', as: :products_update_all
  get '403', to: 'errors#403.html', as: :_403

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accia.rb
class Accia < ApplicationRecord

  has_many :products

  has_one_attached :image


  def to_param
    "#{id}-#{slug}"
  end
  
end

app/models/accion_iterator.rb
class AccionIterator < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user
  has_many :positions
  has_many :products, through: :positions

  def to_param
    "#{id}-#{slug}"
  end


  private

  def set_slug
    self.slug = self.user.name.to_s.parameterize + "cart"
  end
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products
  has_ancestry

  validates :name, presence: true

  def to_param
    "#{id}-#{slug}"
  end


  private

  def set_slug
    self.slug = self.name.to_s.parameterize
  end
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
  has_many :positions
  has_many :products, through: :positions

  def to_param
    "#{id}-#{slug}"
  end

  private

  def set_slug
    self.slug = self.user.name.to_s.parameterize + "order" + self.id
  end
end

app/models/position.rb
class Position < ApplicationRecord

  validates :quantity, presence: true, numericality: { greater_than: 0, less_than: 100 }

  belongs_to :product
  belongs_to :cart
  belongs_to :order
end

app/models/post.rb
class Post < ApplicationRecord

  def to_param
    "#{id}-#{slug}"
  end


  private

  def set_slug
    self.slug = self.title.to_s.parameterize
  end
end

app/models/product.rb
class Product < ApplicationRecord

  validates :name, length: { maximum: 52,
   too_long: "Наименование не должно превышать 52 символов" }

  belongs_to :category
  belongs_to :accia

  has_one :productcount

  has_many :positions
  has_many :carts, through: :positions
  has_many :orders, through: :positions

  has_one_attached :image

  def to_param
    "#{id}-#{slug}"
  end

  private

  def set_slug
    self.slug = self.name.to_s.parameterize
  end

end

app/models/productcount.rb
class Productcount < ApplicationRecord
    belongs_to :product
end

app/models/review.rb
class Review < ApplicationRecord

  def to_param
    "#{id}-#{slug}"
  end

  private

  def set_slug
    self.slug = title.to_s.parameterize
  end 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders
  has_one :cart


  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :confirmable, :validatable

  def to_param
    "#{id}-#{slug}"
  end

  private

  def set_slug
    self.slug = self.name.to_s.parameterize
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :find_cart, only: [:edit, :show, :update, :destroy]

  def index
    
  end

  def show

  end

  def new
  end

  def edit

  end

  def destroy
  end

  def update

  end

  def cart_params
    params.require(:cart).permit(:id, :user_id, :product_ids)
  end

  def position_params
    params.require(:position).permit(:id, :cart_id, :product_id, :quantity)
  end

  def product_params
    params.require(:product).permit(:id, :name, :image)
  end

  def find_cart
    @cart = Cart.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
  end

  def show
    @cart = Cart.find(@user.cart_id)
  end

  def edit
  end

  def destroy
  end

  def update
    @user.update(name: params[:user][:name], email: params[:user][:email],  city: params[:user][:city],  telephone: params[:user][:telephone])
    redirect_to user_path(@user)
  end

  def user_params
    params.require(:user).permit(:id, :name, :email, :cart_id, :slug, :telephone, :city)
  end

  def cart_params
    params.require(:cart).permit(:id, :user_id, :slug)
  end

  def position_params
    params.require(:position).permit(:id, :product_id, :quantity)
  end

  def product_params
    params.require(:product).permit(:id, :name, :slug)
  end

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/accia_helper.rb
module AcciaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/startpage_helper.rb
module StartpageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <script src="http://code.jquery.com/jquery-latest.js"></script>

    <title>JollyTail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      .logo1 {
        font-family: Bell MT, serif;
        font-size: 64px;
        margin-top: 0px;
        vertical-align: top;
        color: Blue;
        font-weight: bold;
      }
      .logo2 {
        font-family: Bell MT, serif;
        font-size: 64px;
        margin-top: 0px;
        vertical-align: top;
        color: #00ff00;
        font-weight: bold;
      }
      hr {
        display: block;
        height: 1px;
        border: 0;
        border-top: 2px solid Green;
        /*margin: 1em 0;*/
        padding: 0;
      }
      .mainhead {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 24px;
        background-color: #4b0082;
        background-color: #4b0082f9;
        margin: 0px;
      }
      a {
        text-decoration: none !important;
        color: inherit !important; /* Отменяем подчеркивание у ссылки */
      }
      .user_menu_head {
        color: Green;
        font-family: Arial, Helvetica, sans-serif;
        font-size: 16px;
        vertical-align: top;
        text-align: left;
        width: 100%
      }
      .start_user_menu {
        color: Green;
        font-family: Arial, Helvetica, sans-serif;
        font-size: 16px;
        vertical-align: top;
        text-align: left;
        width: 100%
      }
      .user_menu_body {
        font-family: Arial, Helvetica, sans-serif;
        color: Blue;
        font-size: 12px;
        vertical-align: top;
        text-align: left;
        margin: 0px;
        width: 100%
      }
      .adress_table {
        display: table-cell;
        text-align: left;
        font-size: 12px;
        margin-top: 10px;
        margin-bottom: 10px;
        vertical-align: top;
      }
      .divider{
        display: table-cell;
        width: 1%;
      }
      .long_divider{
        display: table-cell;
        width: 5%;
      }
      .credo{
        font-family: Bell MT, serif;
        position: absolute;
        margin-top: 78px;
        margin-left: 300px;
        font-weight: bold;
        font-style: oblique;
        font-size: 24px;
        color: Blue;
      }
      li{
        list-style-type: none;
      }
      img{
        margin-top: 0px;
      }
      input[type=submit] {
        padding:10px 15px !important;
        margin-left: 5px !important;
        background: Green !important;
        border:0 none !important;
        cursor: pointer !important;
        -webkit-border-radius: 5px !important;
        border-radius: 5px !important;
      }
      button {
        padding:10px 15px !important;
        font-size: 24px;
        margin-left: 5px !important;
        background: Green !important;
        border:0 none !important;
        cursor: pointer !important;
        -webkit-border-radius: 5px !important;
        border-radius: 5px !important;
      }
      button:hover {
        background: Purple !important;
      }
      #page-container {
        position: relative;
        min-height: 100vh;
      }
      #content-wrap {
        padding-bottom: 10rem;    /* Footer height */
      }
      #footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        height: 2rem;            /* Footer height */
      }

      </style>
    </head>

  <body>
    <div id="page-container">
      <div id="content-wrap">
  <div style="position: relative; top: 0;">
  <div class="credo">Друзья ваших друзей</div>
  <div style="position: absolute; margin-left: 72%; margin-top: 42.5px;"><%= image_tag "jolly_all.png", size: "200x100" %></div>
  <div style="position: absolute; color: Purple; font-size: 20px; font-weight: bold; margin-top: 0px; margin-left: 115px;">Товары для животных</div>
  <div style="display: table; vertical-align: middle">
    <div style="display: table-row">

        <div style="display: table-cell; vertical-align: middle; width: 8%;">
          <%= link_to image_tag("JT_logo2.png", size: "110x110"), root_url %>
        </div>

        <div style="display: table-cell; width: 24%; text-align: left; vertical-align: middle;">
          <span class="logo1">Jolly</span><span class="logo2">Tail</span>
        </div>
        <div class="long_divider"></div>
        <div style="display: table-cell; width: 80px;">
          <%= image_tag "jollydog.jpg", size: "73x110" %>

        </div>
        <div class="adress_table" style="width: 8%; font-weight: bold;">
          Где нас найти:<br>
          г. Екатеринбург<br>
          Сулимова 42 <br>
        </div>

        <div class="divider"></div>
        <div class="adress_table" style="width: 12%; font-weight: bold;">
            Как с нами связаться:<br>
            Телефон: +7-950-546-20-85<br>
            e-mail: e-mail<br>
            Viber: e-mail<br>
            WhatsApp: e-mail<br>
        </div>
        <div class="divider"></div>
        <div class="adress_table" style="width: 12%; font-weight: bold;">
            Мы работаем:<br>
            пн-вс: 10:00 до 21:00
        </div>

        <div class="long_divider"></div>
        <div class="long_divider"></div>
        <div class="divider"></div>
        <div style="display: table-cell; height: 20px; vertical-align: top;">
          <% if user_signed_in? %>
            <span class="user_menu_head" style=""><%= current_user.name %></span>
            <table class="user_menu_body" style="display: none; background-color: White;">
              <tr><th><%= link_to "Личный кабинет",  user_path(current_user)  %></th></tr>
              <tr><th><%= link_to "Корзина",  user_path(current_user, :param1 => "start") %><span id="cartcountid" style="color: Purple"><%= current_user.cart.positions ? " " + current_user.cart.positions.size.to_s : "" %></span></th></tr>
              <tr><th><%= link_to "Выход",  destroy_user_session_path, method: :delete  %></th></tr>
            </table>

          <% else %>
            <span class="start_user_menu" style="color: Blue;"><%= link_to("Вход",  new_user_session_path) %></span>
            <span class="start_user_menu"><%= link_to("Регистрация",  new_user_registration_path) %> </span>
          <% end %>
        </div>

      </div>
  </div>


  <div class="mainhead" style=" background-color: #a580a9; width: 100%; margin: 0px;">
  <table style="text-align: center; width: 100%; padding: 0px;">
    <tr style="margin: 0px; padding: 0px;">
      <th id="categ_main" class="mainhead_point" style="padding: 0px; width: 8%; text-align: center;"><%= link_to("Каталог", categories_path) %></th>
      <th id="acti_main" class="mainhead_point" style="padding: 0px; width: 8%; text-align: center;"><%= link_to("Акции", accias_url) %></th>
      <th id="about_main" class="mainhead_point" style="padding: 0px; width: 8%; text-align: center;"><%= link_to("Контакты", credits_url) %></th>
      <th id="logist_main" class="mainhead_point" style="padding: 0px; width: 17%; text-align: center;"><%= link_to("Доставка и оплата", delivery_url) %></th>
      <th id="revi_main" class="mainhead_point" style="padding: 0px; width: 8%; text-align: center;"><%= link_to("Отзывы", reviews_path) %></th>
      <th style="font-size: 16px; width: 100%; padding-right: 0px;">
        <%= form_tag(products_url, method: :get)  do %>
            <%= text_field_tag(:q, (params[:q] ? params[:q] :'Поиск...'), id: 'search')%><%= submit_tag("Поиск") %>
        <% end %>
      </th>
    </tr>
  </table>

  </div>
  </div>

  <h1 stile="color: Green;" class="notice"><%= notice %></h1>
  <h1 stile="color: Green;" class="alert"><%= alert %></h1>

    <%= yield %>
</div>

    <footer id="footer" style=" background-color: #a580a9;">
      <table>
        <tr>
          <th>
            <span style="font-size: 16px;"> <%= link_to "Политика конфиденциальности", politic_url%></span>
          </th>
        </tr>
        <tr>
          <th>
            <span style="">На сайте использованы изображения с ресурса:<a href=https://ru.pngtree.com>Графика от pngtree.com</a></span>
          </th>
        </tr>
      </table>
    </footer>
</div>
  </body>
</html>

<script>
  $(document).ready(function(){
      var i = false;
      var buf_color = "";
      var countcart = 0;
      $(".product_onse_placer .new_position .product_count_placer").hide();
      $('#search').one('click', function(e) { $(this).val(""); });
      $(".user_menu_head").on({ mouseenter: function() {
                                                        $(".user_menu_body").show();
                                                        } });
      $(".mainhead").on({ mouseenter: function() {
                                                        $(".user_menu_body").hide();
                                                 } });
      $(".mainhead_point").on({ mouseenter: function() {
                                                        buf_color = $(this).css("background-color");
                                                        $(this).css("background-color", "Green");
                                                        i = true;
                                                       } });
      $(".mainhead_point").on({ mouseleave: function() {
                                                        if (i == true) { $(this).css("background-color", buf_color); }
                                                        i = false;
                                                       } });
      $(".product_onse_placer").on({ mouseenter: function() {
                                                              $(this).find(".new_position .product_count_placer").show();
                                                            } });
      $(".product_onse_placer").on({ mouseleave: function() {
                                                              $(this).find(".new_position .product_count_placer").hide();
                                                            } });
  });
</script>

app/views/shared/_cartcount.html.erb
<%= current_user.cart.positions ? " " + current_user.cart.positions.size.to_s : "" %>

app/views/shared/_productonce.html.erb
<div class="product_onse_placer", style="display:table-cell; width: 300px; border: 1px solid #4b0082; text-align: center;">

  <h2 style="margin-top: 5px; margin-bottom: 0px; color: Black; font-size: 18px;"><%= link_to e.name, product_path(e) %></h2>

  <% if e.name.size < 40 %> <br style="margin-top: 0px; margin-bottom: 0px; color: Black; font-size: 18px;"> <% else %> <% end %>

  <% if e.image.attached? %>
      <%= image_tag(url_for(e.image), size: "150x150") %>
  <% else %>
      <%= image_tag("default_foto.jpg", size: "150x150") %>
  <% end %>
  <br>
  <% @accia = Accia.find(e.accia_id) %>
    <% @starttime = @accia.starttime %>
    <% @time = Time.now(); %>
    <% @endtime = @accia.endtime %>
  <% if (@time > @starttime) && (@time < @endtime) %>
      <span class="price" style="font-size: 20px; color: Red;">Цена по акции: <%= e.action_price %> p.</span><br>
  <% else %>
      <span class="price" style="font-size: 20px; color: Purple;"><%= e.price %> p.</span><br>
  <% end %>


  <% if e.productcount %>
      <% if user_signed_in? %>
            <span style="font-size: 26px; color: Green;">
                <%= form_for Position.new, remote: true do |f| %>
                <span class="product_count_placer"><%= f.text_field :quantity, type: "number", value: 1, min: 0, max: e.productcount.count, :style => "width: 60px" %> шт.</span>
                <%= f.hidden_field :prod_id, :value => e.id%>
                <%= f.submit "В корзину"%>
              <% end %>
            </span>
      <% else %>
          <%= button_tag(type: 'button') do %>
          <%= link_to "В корзину",  new_user_session_url %>
          <% end %>
      <% end %>
  <% else %>
      <h2>Заказать</h2>
  <% end %>

</div>

app/views/shared/_tree.html.erb
<h2>Каталог</h2>

    <% Category.roots.each do |category| %>

      <% if category.real %>

        <% if category.children? == true %>
          <span class="sub" style="font-size: 16px; cursor: pointer;"> > <span class="cat_point" style="color: Blue;"><%=link_to(category.name, category_path(category))%></span></span>
          <br>
          <ul style="display: none;"><%= render "shared/tree_adding", main_cat: category.children %></ul>
        <% else %>
          <span style="font-size: 16px; cursor: pointer; margin-left: 14px;"> <span class="cat_point" style="color: Black;"><%=link_to(category.name, category_path(category))%></span></span><br>
        <% end %>

      <% end %>

    <% end %>

<script>
      $(document).ready(function() {
          var $sidebarArrow = $('.sub');
          $sidebarArrow.click(function() {
              $(this).next().next().slideToggle();
          });
      });
</script>

app/views/shared/_tree_adding.html.erb
<% main_cat.each do |category| %>

      <% if category.children? == true %>

          <li> <span class="sub" style="font-size: 14px; cursor: pointer;"> > <span class="cat_point" style="color: Green;"><%= link_to(category.name, category_path(category)) %> </span></span>
            <br>
          <ul style="font-size: 14px; display: none;">
              <%= render "shared/tree_last", main_cat: category.children %>
          </ul>

          </li>


         <% else %>
             <li><span class="cat_point"><%= link_to(category.name, category_path(category)) %><span></li>
         <% end %>

<% end %>

app/views/shared/_tree_last.html.erb
<% main_cat.each do |category| %>
  <li> <span  class="cat_point" ><%= link_to(category.name, category_path(category)) %> </span></li>
<% end %>